<?php

namespace Proxies\__CG__\Registronetbook\ControlBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Registronetbook\ControlBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'dni', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'cuil', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'mail', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'direccion', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'descripcion', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'anulado', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'fechaAlta', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'fechaBaja', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'turno', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'egresado', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'tipo', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'appUser', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'curso');
        }

        return array('__isInitialized__', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'dni', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'cuil', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'mail', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'direccion', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'descripcion', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'anulado', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'fechaAlta', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'fechaBaja', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'turno', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'egresado', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'tipo', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'appUser', '' . "\0" . 'Registronetbook\\ControlBundle\\Entity\\Usuario' . "\0" . 'curso');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDni($dni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDni', array($dni));

        return parent::setDni($dni);
    }

    /**
     * {@inheritDoc}
     */
    public function getDni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDni', array());

        return parent::getDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuil($cuil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuil', array($cuil));

        return parent::setCuil($cuil);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuil', array());

        return parent::getCuil();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', array($mail));

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', array());

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnulado($anulado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnulado', array($anulado));

        return parent::setAnulado($anulado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnulado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnulado', array());

        return parent::getAnulado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', array($fechaAlta));

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', array());

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaBaja($fechaBaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaBaja', array($fechaBaja));

        return parent::setFechaBaja($fechaBaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaBaja', array());

        return parent::getFechaBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setTurno($turno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurno', array($turno));

        return parent::setTurno($turno);
    }

    /**
     * {@inheritDoc}
     */
    public function getTurno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurno', array());

        return parent::getTurno();
    }

    /**
     * {@inheritDoc}
     */
    public function setEgresado($egresado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEgresado', array($egresado));

        return parent::setEgresado($egresado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEgresado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEgresado', array());

        return parent::getEgresado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppUser(\Registronetbook\UserBundle\Entity\AppUser $appUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppUser', array($appUser));

        return parent::setAppUser($appUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppUser', array());

        return parent::getAppUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurso(\Registronetbook\ControlBundle\Entity\Curso $curso = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurso', array($curso));

        return parent::setCurso($curso);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurso', array());

        return parent::getCurso();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
